version: '3'
services:
    postgres:
        image: postgres:10-alpine
        container_name: postgres
        expose:
            - '5432'
        ports:
            - '5432:5432'
        environment:
            - PG_PASSWORD=password
            - POSTGRES_PASSWORD=password
